window.DEFAULT_MENU = [
  {id:"kofta", ar:"كفتة", en:"Kofta", price:25, cat:"grill", img:"kofta.jpg"},
  {id:"shish", ar:"شيش طاووق", en:"Shish Taouk", price:28, cat:"grill", img:"shish-taouk.jpg"},
  {id:"kebab", ar:"كباب", en:"Kebab", price:30, cat:"grill", img:"kofta.jpg"},
  {id:"mutton", ar:"ريش غنم", en:"Mutton Chop", price:30, cat:"grill", img:"mutton-chop.jpg"},
  {id:"mix", ar:"مشوي مشكل عادي", en:"Regular Mix Grill", price:30, cat:"grill", img:"shish-taouk.jpg"},
  {id:"mixplus", ar:"مشوي مشكل مع ريش ٢ قطعة", en:"Mix Grill + 2 Mutton Chops", price:35, cat:"grill", img:"mutton-chop.jpg"},
  {id:"boneless", ar:"١/٢ مسحب", en:"Half Boneless Chicken", price:30, cat:"grill", img:"grilled-wings.jpg"},
  {id:"machine-half", ar:"١/٢ دجاج مكنة", en:"Half Chicken Machine", price:16, cat:"grill", img:"tajin-chicken.jpg"},
  {id:"machine-quarter", ar:"١/٤ دجاج مكنة", en:"Quarter Chicken Machine", price:10, cat:"grill", img:"tajin-chicken.jpg"},
  {id:"wings", ar:"جوانح مشوية", en:"Grilled Wings", price:20, cat:"grill", img:"grilled-wings.jpg"},
  {id:"tarab", ar:"طراب", en:"Tarab", price:30, cat:"grill", img:"mutton-chop.jpg"},
  {id:"kofta-kilo", ar:"كفتة ١ كيلو", en:"Kofta 1 Kilo", price:90, cat:"grill", img:"kofta.jpg"},
  {id:"taouk-kilo", ar:"طاووق ١ كيلو", en:"Taouk 1 Kilo", price:95, cat:"grill", img:"shish-taouk.jpg"},
  {id:"mutton-kilo", ar:"ريش ١ كيلو", en:"Mutton Chop 1 Kilo", price:120, cat:"grill", img:"mutton-chop.jpg"},
  {id:"kebab-kilo", ar:"كباب ١ كيلو", en:"Kebab 1 Kilo", price:100, cat:"grill", img:"kofta.jpg"},
  {id:"mix-kilo", ar:"مشوي مشكل ١ كيلو", en:"Mix Grill 1 Kilo", price:100, cat:"grill", img:"shish-taouk.jpg"},
  {id:"mix-mutton-kilo", ar:"مشوي مشكل مع ريش ١ كيلو", en:"Mix Grill With Mutton Chop 1 Kilo", price:120, cat:"grill", img:"mutton-chop.jpg"},
  {id:"tarab-kilo", ar:"طراب ١ كيلو", en:"Tarab 1 Kilo", price:100, cat:"grill", img:"grilled-wings.jpg"},

  {id:"molokhia", ar:"ملوخية بالفراخ", en:"Molokhia With Chicken", price:22, cat:"tajin", img:"molokhia.jpg"},
  {id:"molokhia-meat", ar:"ملوخية باللحمة", en:"Molokhia With Meat", price:25, cat:"tajin", img:"molokhia.jpg"},
  {id:"okra", ar:"بامية باللحمة", en:"Okra With Meat", price:25, cat:"tajin", img:"tajin-chicken.jpg"},
  {id:"pigeon-potato", ar:"طاجن حمام بالبطاطس", en:"Pigeon With Potatoes", price:80, cat:"tajin", img:"fatteh.jpg"},
  {id:"beans-meat", ar:"فاصوليا باللحمة", en:"White Beans With Meat", price:25, cat:"tajin", img:"tajin-chicken.jpg"},
  {id:"tajin-neva", ar:"طاجن نيفا", en:"Tajin Neva", price:30, cat:"tajin", img:"tajin-chicken.jpg"},
  {id:"tajin-rice", ar:"جميع الطواجن مع أرز وشوربة", en:"All Tajin Served With Rice & Soup", price:0, cat:"tajin", img:"tajin-chicken.jpg"},
  {id:"boiled-chicken", ar:"دجاج مسلوق مع لسان عصفور", en:"Boiled Chicken With Soup", price:14, cat:"tajin", img:"tajin-chicken.jpg"},
  {id:"boiled-meat", ar:"لحم مسلوق مع لسان عصفور", en:"Boiled Meat With Soup", price:15, cat:"tajin", img:"mutton-chop.jpg"},

  {id:"lamb-fatteh", ar:"فتة موزة", en:"Lamb Fatteh", price:32, cat:"main", img:"fatteh.jpg"},
  {id:"mansaf", ar:"منسف أردني", en:"Jordanian Mansaf", price:45, cat:"main", img:"fatteh.jpg"},
  {id:"chicken-biryani", ar:"برياني دجاج", en:"Chicken Biryani", price:20, cat:"main", img:"biryani.jpg"},
  {id:"mutton-biryani", ar:"برياني لحم", en:"Mutton Biryani", price:25, cat:"main", img:"biryani.jpg"},
  {id:"mix-stuffed", ar:"محاشي مشكل", en:"Mix Stuffed", price:20, cat:"main", img:"vine-leaves.jpg"},
  {id:"oven-chicken", ar:"دجاج في الفرن", en:"Oven Baked Chicken", price:22, cat:"main", img:"fatteh.jpg"},
  {id:"fattoush-chicken", ar:"مكرونة فتوشي دجاج", en:"Fattoush Chicken", price:20, cat:"main", img:"salad.jpg"},
  {id:"pasta", ar:"مكرونة بشاميل لحم", en:"Pasta With Meat & Bechamel", price:15, cat:"main", img:"biryani.jpg"},
  {id:"bolognese", ar:"سباجيتي بولونيز", en:"Spaghetti Bolognese", price:15, cat:"main", img:"biryani.jpg"},

  {id:"fool-isk", ar:"فول اسكندراني", en:"Fool Iskandrani", price:12, cat:"breakfast", img:"falafel.jpg"},
  {id:"fool-tahini", ar:"فول بالطحينة", en:"Fool With Tahini", price:12, cat:"breakfast", img:"falafel.jpg"},
  {id:"falafel", ar:"فلافل ٦ حبة", en:"6 Pieces Falafel", price:10, cat:"breakfast", img:"falafel.jpg"},
  {id:"liver-breakfast", ar:"كبدة اسكندراني", en:"Iskandrani Liver", price:15, cat:"breakfast", img:"liver.jpg"},
  {id:"liver-cheese", ar:"كبدة جبن", en:"Liver Cheese", price:18, cat:"breakfast", img:"liver.jpg"},
  {id:"veg-omelet", ar:"أومليت بالخضار", en:"Vegetable Omelet", price:10, cat:"breakfast", img:"falafel.jpg"},
  {id:"cheese-omelet", ar:"أومليت جبن", en:"Cheese Omelet", price:12, cat:"breakfast", img:"falafel.jpg"},
  {id:"shakshuka", ar:"شكشوكة", en:"Shakshuka", price:10, cat:"breakfast", img:"liver.jpg"},

  {id:"lentil", ar:"شوربة عدس", en:"Lentil Soup", price:6, cat:"soups", img:"soup.jpg"},
  {id:"chicken-soup", ar:"شوربة دجاج كريمه", en:"Cream Of Chicken Soup", price:8, cat:"soups", img:"soup.jpg"},
  {id:"veg-soup", ar:"شوربة خضار", en:"Vegetable Soup", price:5, cat:"soups", img:"soup.jpg"},
  {id:"orzo", ar:"شوربة لسان عصفور", en:"Orzo Soup", price:5, cat:"soups", img:"soup.jpg"},

  {id:"hummus", ar:"حمص", en:"Hummus", price:10, cat:"appetizers", img:"vine-leaves.jpg"},
  {id:"olive", ar:"سلطة زيتون", en:"Olive Salad", price:8, cat:"appetizers", img:"salad.jpg"},
  {id:"cucumber-yogurt", ar:"روب خيار", en:"Cucumber With Yogurt", price:6, cat:"appetizers", img:"vine-leaves.jpg"},
  {id:"rocket", ar:"سلطة جرجير", en:"Rocket Salad", price:12, cat:"appetizers", img:"salad.jpg"},
  {id:"mutabbal", ar:"متبل", en:"Mutabbal", price:10, cat:"appetizers", img:"vine-leaves.jpg"},
  {id:"yogurt", ar:"لبنة", en:"Condensed Yoghurt", price:10, cat:"appetizers", img:"vine-leaves.jpg"},
  {id:"cold-vine", ar:"ورق عنب بارد", en:"Vine Leaves Cold", price:10, cat:"appetizers", img:"vine-leaves.jpg"},
  {id:"green-salad", ar:"سلطة خضراء", en:"Green Salad", price:8, cat:"appetizers", img:"salad.jpg"},
  {id:"fattoush", ar:"فتوش", en:"Fattoush", price:10, cat:"appetizers", img:"salad.jpg"},
  {id:"plate-large", ar:"صحن مقبلات كبير", en:"Appetizer Plate Large", price:45, cat:"appetizers", img:"salad.jpg"},
  {id:"plate-small", ar:"صحن مقبلات صغير", en:"Appetizer Plate Small", price:20, cat:"appetizers", img:"salad.jpg"},

  {id:"cheese-samosa", ar:"سمبوسة جبن", en:"Cheese Samosa", price:10, cat:"hot", img:"hot-appetizers.jpg"},
  {id:"meat-hummus", ar:"حمص لحم", en:"Meat With Hummus", price:15, cat:"hot", img:"hot-appetizers.jpg"},
  {id:"spicy-potato", ar:"بطاطا حارة", en:"Spicy Potatoes", price:10, cat:"hot", img:"hot-appetizers.jpg"},
  {id:"fried-kebab", ar:"كبة مقلية ٥ حبة", en:"Fried Kebab 5 Pieces", price:12, cat:"hot", img:"hot-appetizers.jpg"},
  {id:"chicken-liver-hot", ar:"كبدة دجاج", en:"Chicken Liver", price:12, cat:"hot", img:"hot-appetizers.jpg"},
  {id:"fried-potato", ar:"بطاطا مقلية", en:"Fried Potatoes", price:6, cat:"hot", img:"hot-appetizers.jpg"},
  {id:"sausage", ar:"سجق", en:"Sausage", price:15, cat:"hot", img:"hot-appetizers.jpg"},
  {id:"spicy-chicken", ar:"الدجاج الحار", en:"Spicy Chicken", price:12, cat:"hot", img:"hot-appetizers.jpg"},
  {id:"rice", ar:"طلب أرز", en:"Rice", price:6, cat:"hot", img:"biryani.jpg"},

  {id:"shawarma-small", ar:"شاورما دجاج صغير", en:"Chicken Shawarma Small", price:7, cat:"sandwiches", img:"shawarma.jpg"},
  {id:"shawarma-large", ar:"شاورما دجاج كبير", en:"Chicken Shawarma Large", price:12, cat:"sandwiches", img:"shawarma.jpg"},
  {id:"falafel-sandwich", ar:"ساندوتش فلافل", en:"Falafel Sandwich", price:4, cat:"sandwiches", img:"shawarma.jpg"},
  {id:"kofta-sandwich", ar:"ساندوتش كفتة", en:"Kofta Sandwich", price:12, cat:"sandwiches", img:"kofta.jpg"},
  {id:"spicy-chicken-sandwich", ar:"ساندوتش الدجاج مكسيكي الحار", en:"Spicy Mexican Chicken", price:12, cat:"sandwiches", img:"shawarma.jpg"},
  {id:"liver-sandwich", ar:"ساندوتش كبدة", en:"Liver Sandwich", price:12, cat:"sandwiches", img:"liver.jpg"},
  {id:"shawarma-plate", ar:"صحن شاورما دجاج", en:"Chicken Shawarma Plate", price:28, cat:"sandwiches", img:"shawarma-platter.jpg"},
  {id:"burger", ar:"ساندوتش برجر لحم", en:"Hamburger Beef", price:15, cat:"sandwiches", img:"burger.jpg"},
  {id:"loly", ar:"ساندوتش لولي بوب", en:"Loly Pop", price:12, cat:"sandwiches", img:"shawarma.jpg"},
  {id:"rubian", ar:"ساندوتش روبيان", en:"Rubian", price:10, cat:"sandwiches", img:"shawarma.jpg"},
  {id:"hawawshi", ar:"حواوشي", en:"Hawawshi", price:12, cat:"sandwiches", img:"shawarma.jpg"},

  {id:"rice-milk", ar:"أرز باللبن", en:"Rice With Milk", price:5, cat:"dessert", img:"rice-milk.jpg"},
  {id:"cream-caramel", ar:"كريم كراميل", en:"Cream Caramel", price:8, cat:"dessert", img:"cream-caramel.jpg"},
  {id:"pudding", ar:"مهلبية", en:"Pudding", price:5, cat:"dessert", img:"rice-milk.jpg"},
  {id:"om-ali", ar:"أم علي", en:"Om Ali", price:12, cat:"dessert", img:"cream-caramel.jpg"},
  {id:"kunafa", ar:"كنافة بالجبن", en:"Knafeh With Cheese", price:14, cat:"dessert", img:"cream-caramel.jpg"},

  {id:"soft-drink", ar:"مشروبات غازية", en:"Soft Drink", price:3, cat:"drinks", img:"mango-juice.jpg"},
  {id:"water", ar:"مياه معدنية", en:"Mineral Water", price:2, cat:"drinks", img:"mango-juice.jpg"},
  {id:"tea", ar:"شاي", en:"Tea", price:2, cat:"drinks", img:"coffee.jpg"},
  {id:"coffee", ar:"قهوة", en:"Coffee", price:6, cat:"drinks", img:"coffee.jpg"},
  {id:"mango", ar:"عصير مانجو", en:"Mango Juice", price:12, cat:"drinks", img:"mango-juice.jpg"},
  {id:"orange", ar:"عصير برتقال", en:"Orange Juice", price:12, cat:"drinks", img:"mango-juice.jpg"},
  {id:"mint-lemon", ar:"عصير ليمون نعناع", en:"Mint Lemon Juice", price:10, cat:"drinks", img:"mango-juice.jpg"},

  {id:"grape-leaves-lamb", ar:"خروف محشي ورق عنب", en:"Lamb Stuffed With Grape Leaves", price:0, cat:"special", img:"special.jpg"},
  {id:"half-lamb", ar:"١/٢ خروف محشي ورق عنب", en:"Half Lamb Stuffed With Grape Leaves", price:0, cat:"special", img:"special.jpg"},
  {id:"quarter-lamb", ar:"١/٤ فخذة خروف", en:"Quarter Lamb Thigh", price:0, cat:"special", img:"special.jpg"},
  {id:"roast-chicken", ar:"طبق دجاج محشي برياني أو مكبوس يكفي ٦ أشخاص", en:"Roasted Chicken With Rice For 6", price:150, cat:"special", img:"special.jpg"},
  {id:"biryani-chicken-6", ar:"طبق دجاج برياني أو مكبوس أو جريتر يكفي ٦ أشخاص", en:"Biryani Chicken For 6", price:150, cat:"special", img:"special.jpg"},
  {id:"turkey-6", ar:"طبق ديك رومي يكفي ٦ أشخاص", en:"Turkey For Six Persons", price:150, cat:"special", img:"special.jpg"},
  {id:"grilled-chicken", ar:"دبك رومي مشوي يكفي ٦ أشخاص", en:"Grilled Chicken For 6", price:250, cat:"special", img:"special.jpg"},
  {id:"mansaf-6", ar:"صينية منسف أردني تكفي ٦ أشخاص", en:"Jordanian Mansaf For 6", price:270, cat:"special", img:"special.jpg"},
  {id:"grilled-pigeon-2", ar:"حمام مشوي ٢ حبة", en:"Grilled Pigeon 2", price:82, cat:"special", img:"grilled-pigeon.jpg"},
  {id:"rice-pigeon", ar:"حمام محشي أرز ٢ حبة", en:"Rice Stuffed Pigeon", price:90, cat:"special", img:"rice-stuffed-pigeon.jpg"}
];;
