
const $=s=>document.querySelector(s);let currentUser=null,orders=[],unsub=null;
const statusLabel={ready:"جاهز للاستلام",on_the_way:"في الطريق",delivered:"تم التسليم"};
function showGate(msg=""){const gate=$("#authGate");gate.hidden=false;gate.innerHTML=`<div class="auth-card"><div class="auth-logo">البرنس <small>FOOD</small></div><span class="auth-eyebrow">DELIVERY ACCESS</span><h1>دخول الدليفري</h1><form id="driverLogin"><label>البريد الإلكتروني<input id="driverEmail" type="email" required></label><label>كلمة المرور<input id="driverPassword" type="password" required></label><button class="auth-submit">دخول</button><div id="driverMsg" class="auth-msg error">${msg}</div></form></div>`;$("#driverLogin").onsubmit=async e=>{e.preventDefault();try{await signInWithEmailAndPassword(auth,$("#driverEmail").value.trim(),$("#driverPassword").value)}catch(err){$("#driverMsg").textContent="البريد أو كلمة المرور غير صحيحة."}}}
async function roleOf(uid){const s=await getDoc(doc(db,"users",uid));return s.exists()?s.data().role:""}
function render(){const box=$("#deliveryOrders");if(!orders.length){box.innerHTML=`<div class="order"><h3>مفيش طلبات مسندة ليك حاليًا</h3><p class="address">أول ما الإدارة تسندلك طلب هيظهر هنا تلقائيًا.</p></div>`;$(".welcome p").innerHTML="مفيش طلبات مسندة ليك حاليًا.";return}$(".welcome p").innerHTML=`عندك <b>${orders.length} طلبات</b> محتاجة متابعة النهارده.`;box.innerHTML=orders.map((o,i)=>`<article class="order"><div class="order-top"><span class="order-id">#${o.id.slice(0,7)} • توصيل</span><span class="status ${o.status==="on_the_way"?"route":"pickup"}">${statusLabel[o.status]||o.status}</span></div><h3>${escapeHtml(o.customer?.name||"عميل")}</h3><div class="address">📍 ${escapeHtml(o.customer?.address||"")}<br>📞 ${escapeHtml(o.customer?.phone||"")}</div><div class="items">${(o.items||[]).map(x=>`<div class="item"><span>${escapeHtml(x.name)} ×${x.qty}</span><b>${x.unitPrice*x.qty} ج</b></div>`).join("")}</div><div class="order-foot"><span class="total">${Number(o.total||0)} ج</span><button class="primary" data-order="${i}">${o.status==="on_the_way"?"تأكيد التسليم":"بدء التوصيل"}</button></div></article>`).join("")}
function escapeHtml(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]))}
async function changeStatus(id,next){await updateDoc(doc(db,"orders",id),{status:next})}
document.addEventListener("click",async e=>{if(e.target.id==="profile")return signOut(auth);if(e.target.id==="refresh")return;const b=e.target.closest("[data-order]");if(!b)return;const o=orders[Number(b.dataset.order)];try{await changeStatus(o.id,o.status==="on_the_way"?"delivered":"on_the_way")}catch(err){console.error(err);toast("تعذر تحديث حالة الطلب")}});
onAuthStateChanged(auth,async user=>{currentUser=user;if(!user){showGate();return}try{const role=await roleOf(user.uid);if(role!=="driver"){await signOut(auth);showGate("الحساب ده مش Driver.");return}$("#authGate").hidden=true;$(".driver b").textContent="مندوب الدليفري";const q=query(collection(db,"orders"),where("driver.uid","==",user.uid));unsub=onSnapshot(q,snap=>{orders=snap.docs.map(d=>({id:d.id,...d.data()})).filter(o=>["ready","on_the_way"].includes(o.status));render()},err=>console.error(err))}catch(e){console.error(e);await signOut(auth);showGate("تعذر التحقق من الصلاحيات.")}});

function toast(t){const x=document.createElement("div");x.textContent=t;x.style.cssText="position:fixed;bottom:20px;left:20px;background:#4f0b1c;color:#fff;padding:12px 16px;border-radius:10px;z-index:9999;font-size:11px";document.body.appendChild(x);setTimeout(()=>x.remove(),2500)}
